version: '3.8'

services:
  backend:
    build: backend/
    ports:
      - "80:7770"
    environment:
      DB_HOST: db
      DB_DATABASE: proyecto
      DB_USER: pinito
      DB_PASSWORD: pinito123
    networks:
      - red
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: pinito
      POSTGRES_PASSWORD: pinito123
    networks:
      - red
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pinito -d proyecto"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: frontend/
    ports:
      - "8100:7777"
    networks:
      - red      
    depends_on:
      - backend
    environment:
      - BACKEND_IP   

networks:
  red:
    driver: bridge      